### ISSUE TITLE
AP vs Station mode

### ISSUE THREAD

**Issue by benji2020** [jerickso/Twitch-OnAir-Sign#1]
Hi

Thanks for updating the code, I was going round in circles trying to update it myself!

One thing I noticed though is my board was stuck in AP mode. Apparently (not mentioned in many places!) you have to set it each time in setup with:

WiFi.mode(WIFI_STA);

Not sure if it is worth adding, even if commented out?

Regards
Ben

**Comment by jerickso** [comment]
Thanks for the suggestion, @benji2020.  Initially, I don't see a problem with adding that line to the setup function since station mode is how it will be connecting to the network.  I'll test it out on my setup just to make sure there are no crazy side effects.

**Comment by jerickso** [comment]
Added the suggested change in commit f268fb2b36142165a8e8240eaeb6aaa4cb1de0e3.
